# Generated by Django 2.0.6 on 2018-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('send_coin_type', models.CharField(max_length=10)),
                ('recv_coin_type', models.CharField(max_length=10)),
                ('recv_address', models.CharField(max_length=200)),
                ('refund_address', models.CharField(max_length=200)),
            ],
        ),
    ]
