# Generated by Django 2.0.6 on 2018-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0002_exchangeorder_send_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeorder',
            name='send_address',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
