# Generated by Django 2.0.6 on 2018-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0003_auto_20180613_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='max_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='min_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
