# Generated by Django 2.0.6 on 2018-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0004_auto_20180613_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('confirmations', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('blockhash', models.CharField(default=None, max_length=200)),
                ('blockindex', models.IntegerField(default=0)),
                ('blocktime', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('timereceived', models.IntegerField(default=0)),
                ('hex', models.CharField(max_length=500)),
                ('fee', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('vout', models.IntegerField(blank=True, default=0)),
                ('fee', models.FloatField(blank=True, default=0)),
                ('abandoned', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='transaction_list',
            field=models.ManyToManyField(to='coin_exchanger.Transaction'),
        ),
    ]
