# Generated by Django 2.0.6 on 2018-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0005_auto_20180617_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.ManyToManyField(to='coin_exchanger.TransactionDetailInfo'),
        ),
    ]
