# Generated by Django 2.0.6 on 2018-06-20 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0014_auto_20180617_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetailinfo',
            name='detail_id',
        ),
        migrations.AddField(
            model_name='transactiondetailinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
