# Generated by Django 2.0.6 on 2018-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchanger', '0015_auto_20180620_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetailinfo',
            name='abandoned',
            field=models.NullBooleanField(),
        ),
    ]
